apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m9ywh8kqs-dotnet-basic
  janus-idp.io/tekton: m9ywh8kqs-dotnet-basic
  backstage.io/kubernetes-id: m9ywh8kqs-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m9ywh8kqs-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
